[build]
  command = "bash ./netlify-build.sh"
  publish = "public"

# No need for custom environment variables since we're building a static site
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Don't use any plugins
[plugins]

# Handle SPA redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 