[build]
  command = "bash ./netlify-build.sh"
  publish = "public"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Handle SPA redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 